# This file was generated by GoReleaser. DO NOT EDIT.
cask "hooksnode" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "d322f85ac8c7d6bdd443ac8c44eef6e45a99a8a04d9cefb7a9ac5533c5500fef"
      url "https://github.com/mantissatech/hooksnode-cli/releases/download/v#{version}/hooksnode_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a61bc168cfd0a608f03b873986ef992f10633e51045bcf726fd155956cf5e4fe"
      url "https://github.com/mantissatech/hooksnode-cli/releases/download/v#{version}/hooksnode_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7ac51f00424ed1596f52c823befc788ddd523e518d05a3915e0369ec12a8ce10"
      url "https://github.com/mantissatech/hooksnode-cli/releases/download/v#{version}/hooksnode_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ca450d68f811024aace5ad40feefa5b5454d2a94aaa63528b26612cc0b258df"
      url "https://github.com/mantissatech/hooksnode-cli/releases/download/v#{version}/hooksnode_linux_amd64.tar.gz"
    end
  end

  name "hooksnode"
  desc "Forward your project's live inbound webhooks to a local port"
  homepage "https://hooksnode.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hooksnode"

  # No zap stanza required
end
